project:
  type: website
  output-dir: docs

website:
  title: "ES654"
  sidebar:
    background: primary
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: slack
        href: https://join.slack.com/t/es654-2022/shared_invite/zt-1mgeh688j-Wynv7_s_0n2_FaSu7kbUWg
        text: Slack
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: grading.qmd
        text: Grading Policy and FAQ
      - href: schedule.qmd
        text: Schedule
      - href: https://nipunbatra.github.io
        text: Instructor Homepage


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

