---
title: "Grading Policy and FAQ"
---

### Grading Policy

- Quizzes: 60%
    - 10% each
    - Best 6 out of 8
- Assignments: 40%
    - Variable weight (e.g. some assignments would be 5%, some 10%, etc.)
    - Some assignments would involve:
        - Making pull requests to public repositories
        - Writing Hugging Face Spaces like demos
- Bonus: up to 6%
    - Making a non-trivial pull request to a well-starred public repo (4%)
    - Getting the PR accepted (2%)

### FAQ

- What happens if I miss a quiz due to any reason?
    - The quiz will be marked as 0.
    - The provision of best 6 out of 8 quizzes is designed keeping in mind such scenarios.
- What happens if I miss an assignment due to any reason?
    - There will no extensions for assignments.
- Will the quizzes and end-semester exam be open book? Will I be allowed to carry notes?
    - No, the exams and quizzes will be closed book. You are not permitted to carry notes.
- How soon can I expect to receive my answer sheets back?
    - You should expect to receive answer sheets back in 4-5 working days.
- Is there an end-semester exam or mid-semester exam?
    - No, there is no end-semester exam or mid-semester exam. However, some of the quizzes may be held in the exam slot.
- I have a doubt in the assignment. Whom should I write to?
    - Ask on the slack General channel. 

